spring:
  datasource:
    name: springboot  #????
    url: jdbc:mysql://sh-cynosdbmysql-grp-bfnqd438.sql.tencentcdb.com:20160/danger_manage?useSSL=false
    username: root  #???
    password: Gao200310  #??
    driver-class-name: com.mysql.cj.jdbc.Driver  #???????

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false # 设置为false以便在开发期间可以实时查看模板更改

  resources:
    static-locations:classpath:/templates/


mybatis:
  mapper-locations: classpath:mapper/*.xml  #??????
  type-aliases-package: com.example.software.bean #?????


#logging:
#  level:
#    root: DEBUG
